### ISSUE TITLE
r->mac_address usage

### ISSUE THREAD

**Issue by melak** [octo/librouteros#10]
https://github.com/octo/librouteros/blob/37f73ec25ecf8f311806e74d4ec423687ec8b323/src/ros.c#L84-L87

Isn't there a bit of a discord here? If `r->mac_address` needs to be checked on L86, it can't be used unconditionally on L85 either (else it's back at the original problem of things showing up as null); if it doesn't need to be checked however, why check it on L86?

**Comment by rpv-tomsk** [comment]
Hi!  :-)

My logic was:

1) I have no `r->radio_name`. But I have `r->mac_address`. That is better to output MAC than `(null)` in L85. 
If somebody has no `r->radio_name` AND has no `r->mac_address` - nothing changes for him, `(null)` is in output.

2) I have `r->mac_address` but its unclear for me, if this field will be filled in all cases.
So, I put check in L86.

**Comment by melak** [comment]
OK, fair enough :)
