### ISSUE TITLE
New release is required

### ISSUE THREAD

**Issue by rpv-tomsk** [octo/librouteros#3]
Hi, Florian!

I think new version of this library needs to be released. Can you please do this?

After this we will be able to finish work and merge https://github.com/collectd/collectd/pull/1281

**Comment by rpv-tomsk** [comment]
cc @manio

**Comment by manio** [comment]
:+1:

**Comment by rpv-tomsk** [comment]
Ping!

**Comment by octo** [comment]
@rpv-tomsk I assume #7 fixes this?

**Comment by rpv-tomsk** [comment]
Partially ;-)

There is still no new release in https://github.com/octo/librouteros/releases ...
Should we solve https://github.com/octo/librouteros/issues/4 before 1.1.3 released or will postpone this to 1.1.4 ?

**Comment by manio** [comment]
I've tagged 1.1.3 with another one important fix. I think we may now close this issue if you agree.

**Comment by rpv-tomsk** [comment]
Great news, thanks!
