### ISSUE TITLE
RoS from from version 6.43 will change initial login authorization

### ISSUE THREAD

**Issue by Mantikor** [octo/librouteros#4]
RoS from from version 6.43 will change login authorization, and it seems in 6.42.4 authorization no longer works.
Link to WIKI: https://wiki.mikrotik.com/wiki/Manual:API#Initial_login
Old and new algo for auth:
Login method pre-v6.43:
    First, clients sends /login command.
    Reply contains =ret=challenge argument.
    Client sends second /login command, with =name=username and =response=response.
    In case of error, reply contains =ret=error message.
    In case of successful login client can start to issue commands.
Login method post-v6.43:
    Now client sends username and password in first message.
    Password is sent in plain text.
    in case of error, reply contains =message=error message.
    In case of successful login client can start to issue commands.

**Comment by rpv-tomsk** [comment]
https://forum.mikrotik.com/viewtopic.php?f=21&t=133420&start=250#p665728
* Send /login with username and password in plain text
* if response is with challenge then fall back to old login method
* otherwise check status if login is successful

**Comment by Mantikor** [comment]
@rpv-tomsk i know the auth algorithm

**Comment by manio** [comment]
fwiw: similar change in "python's" librouteros:
https://github.com/luqasz/librouteros/commit/5b685f355fdd9023e15abb6daeb6e46476f02303

**Comment by rpv-tomsk** [comment]
Their way is a bit smarter than just sent password in first attempt )

**Comment by rpv-tomsk** [comment]
@manio 

Mariusz, have you an equipment to make tests of the new auth scheme?
I have no.

Also, I'm going to implement PR 2852 @ collectd, please look, maybe you might be interested.

**Comment by manio** [comment]
Currently 6.43 is only in rc versions, but I think I would have one RB where i can install it... I'll try to code this... I assume there will be no problem to also merge this in collectd by you?

I can see that you have some release plan for all of this librouteros and collectd stuff :)
Great news!

**Comment by rpv-tomsk** [comment]
> I assume there will be no problem to also merge this in collectd by you?

As I understand, new auth scheme will not require librouteros API/ABI changes at all.

Will you simply send real login+password in first try, or will use fake one like "python's" librouteros?

I think 'smart' algo has no much sense, because if anybody is able to snif API data, then they can do MITM and force library to send plain password.

**Comment by manio** [comment]
@rpv-tomsk 
You're right, I've done it as suggested by mikrotik guy on forum.
I've tested it on old and new RouterOS versions and in both cases it is working OK :)
It defaults to new algo (less request-responses) but in case when it encounter the ret challenge, it is falling back to old method.

**Comment by rpv-tomsk** [comment]
Propose to put this into Changelog right now. (after #8 merge to avoid rebase).

**Comment by manio** [comment]
Done, thank you :)
